### PR TITLE
fix: lint errors

### PR DESCRIPTION
**Pull request by gagan-aryan**
### Description
Fixes lint errors introduced in #435

### CODE REVIEW

**Comment by anandxkumar** [comment]
It passes locally!

**Comment by anandxkumar** [comment]
Got the error, it's because locally we are using an old version of `pre-commit`, as soon as I updated the `pre-commit`, it gives the same error on travis

**Comment by anandxkumar** [comment]
@erwanp you may want to look into the issue, tried to replicate travis linting locally, passes locally but fails remotely

**Comment by Supriya1702** [comment]
Hello @anandxkumar, I tried testing linting on my system/ I was able to re-create the error when using the current version of black in `pre-commit-config` - [line- 3](https://github.com/radis/radis/blob/54385385a0297e00fc6b8bc209833519ed17a15a/.pre-commit-config.yaml#L3). If I use it upto version `22.1.0` it gives the same error as on travis:

```
black....................................................................Failed
- hook id: black
- exit code: 1
Traceback (most recent call last):
  File "/home/travis/.cache/pre-commit/repopkv29orr/py_env-python3/bin/black", line 8, in <module>
    sys.exit(patched_main())
  File "/home/travis/.cache/pre-commit/repopkv29orr/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6606, in patched_main
    patch_click()
  File "/home/travis/.cache/pre-commit/repopkv29orr/py_env-python3/lib/python3.8/site-packages/black/__init__.py", line 6595, in patch_click
    from click import _unicodefun  # type: ignore
ImportError: cannot import name '_unicodefun' from 'click' (/home/travis/.cache/pre-commit/repopkv29orr/py_env-python3/lib/python3.8/site-packages/click/__init__.py)
```

But when I use the latest version `22.3.0` it formats all the black linting and passes. You may want to check it on your end!

**Comment by anandxkumar** [comment]
Great catch @Supriya1702, it seems like that is the issue, I have updated the black to the latest version, and seems like the error has been reciprocated and has been fixed

**Comment by anandxkumar** [comment]
@Supriya1702 the issue has been resolved, I would be merging it. You may count it as your contribution :wink:

**Review by anandxkumar — COMMENTED** [review]
Reviewed
